spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quest-app-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

quest:
  app:
    secret:questapp
  expires:
    in: 604800